sqlite:
  - 3.34.0
  - 3.33.0
  - 3.32.3

rdkit:
  - 2020.09.1
  - 2020.09.2
  - 2020.09.3

pin_run_as_build:
  rdkit:
    max_pin: x.x.x
    min_pin: x.x.x
  sqlite:
    max_pin: x.x
    min_pin: x.x
