{% set version = "2021.07.2" %}

package:
  name: chemicalite
  version: {{ version }}

source:
  git_url: https://github.com/rvianello/chemicalite.git
  git_rev: {{ version }}

build:
  number: 0
  include_recipe: False

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - sqlite {{ sqlite }}
    - rdkit {{ rdkit }}
    - eigen
    - catch2
  run:
    - sqlite
    - rdkit

test:
  commands:
    - echo ".load chemicalite" | sqlite3
